apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: example-argo-cluster
spec:
  forProvider:
    initialClusterVersion: "latest"
    location: asia-east1-a
    autoscaling:
      autoprovisioningNodePoolDefaults:
        serviceAccount: helicom-admin # name of the service account
    networkConfig:
      enableIntraNodeVisibility: true
    loggingService: logging.googleapis.com/kubernetes
    monitoringService: monitoring.googleapis.com/kubernetes
    addonsConfig:
      gcePersistentDiskCsiDriverConfig:
        enabled: true
    network: "default"
  writeConnectionSecretToRef:
    namespace: default
    name: gke-conn