apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: example-argo-cluster
spec:
  forProvider:
    initialClusterVersion: "latest"
    location: asia-east1-a
    autoscaling:
      autoprovisioningNodePoolDefaults:
        serviceAccount: default # name of the service account
    networkConfig:
      enableIntraNodeVisibility: true
    loggingService: logging.googleapis.com/kubernetes
    monitoringService: monitoring.googleapis.com/kubernetes
    addonsConfig:
      gcePersistentDiskCsiDriverConfig:
        enabled: true
    network: "default"
  writeConnectionSecretToRef:
    namespace: default
    name: gke-conn
---
apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: crossplane-standard-np
spec:
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: 5
      minNodeCount: 3  
    clusterRef:
      name: example-argo-cluster
    config:  
      serviceAccount: default
      machineType: e2-standard-8
      diskSizeGb: 100
      diskType: pd-standard
      imageType: cos_containerd 
      # labels:
      #   test-label: crossplane-created
      oauthScopes:
      - "https://www.googleapis.com/auth/devstorage.read_only"
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
      - "https://www.googleapis.com/auth/servicecontrol"
      - "https://www.googleapis.com/auth/service.management.readonly"
      - "https://www.googleapis.com/auth/trace.append"      
    initialNodeCount: 3
    locations:
      - "asia-east1-a"
---
apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: crossplane-preemptible-np
spec:
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: 5
      minNodeCount: 3  
    clusterRef:
      name: example-argo-cluster
    config:  
      serviceAccount: default
      machineType: e2-standard-8
      diskSizeGb: 100
      diskType: pd-standard
      imageType: cos_containerd
      # labels:
      #   test-label: crossplane-created
      oauthScopes:
      - "https://www.googleapis.com/auth/devstorage.read_only"
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
      - "https://www.googleapis.com/auth/servicecontrol"
      - "https://www.googleapis.com/auth/service.management.readonly"
      - "https://www.googleapis.com/auth/trace.append"     
      preemptible: true 
      taints: 
      - effect: NO_SCHEDULE
        key: cloud.google.com/gke-preemptible
        value: 'true'
    initialNodeCount: 3
    locations:
      - "asia-east1-a"
    