apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: argo-cd/gke-cluster
    repoURL: https://github.com/gyume2021/cicdct-template
    targetRevision: main
  destination:
    namespace: iac
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    automated:
      selfHeal: true
      prune: true