apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtualservice
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd/virtualservices
    repoURL: https://github.com/gyume2021/cicdct-template
    targetRevision: main
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true