apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-cluster
  namespace: argocd
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd/airflow-helm
    repoURL: https://github.com/gyume2021/cicdct-template.git
    helm: 
      valueFiles: 
      - my-values.yaml
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
