apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: argocd
spec:
  destination:
    namespace: redis-cluster
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: redis-cluster
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.6.0
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true