apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd/airflow-helm
    repoURL: https://github.com/gyume2021/cicdct-template.git
    helm: 
      values: |
        flower:
          service:
            externalPort: 6666
      # valueFiles: 
      # - my-values.yaml
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
