apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myairflow
  namespace: argocd
spec:
  destination:
    namespace: af
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: airflow
    repoURL: https://airflow-helm.github.io/charts
    targetRevision: 8.6.0